### ISSUE TITLE
Cannot create PDFs due to puppeteer/Chromium error

### ISSUE THREAD

**Issue by hhe** [mkrakowitzer/actions-makepdfs#7]
When running `actions-makepdfs@master` I get the following error. A look at https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#chrome-is-downloaded-but-fails-to-launch-on-nodejs-14 suggests that this was a regression introduced with Node 14.0 in April 2020, and that Node 14.1 fixes the issue.
```
/usr/bin/docker run --name mkrakowitzeractionsmakepdfslatest_d195dc --label 87c201 --workdir /github/workspace --rm -e INPUT_MARKDOWN_DIR -e INPUT_OUTPUT_DIR -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/data/data":"/github/workspace" mkrakowitzer/actions-makepdfs:latest
(node:1) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process! spawn /node_modules/puppeteer/.local-chromium/linux-706915/chrome-linux/chrome ENOENT


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:193:20)
    at ChildProcess.helper_js_1.helper.addEventListener (/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:185:85)
    at ChildProcess.emit (events.js:198:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
```

**Comment by mkrakowitzer** [comment]
Should be resolved, can you test for me?

**Comment by geoffrey-vl** [comment]
I'm still seeing this issue using master branch.

```
Run mkrakowitzer/actions-makepdfs@master
  with:
    output_dir: tmp
/usr/bin/docker run --name mkrakowitzeractionsmakepdfslatest_dced75 --label 179394 --workdir /github/workspace --rm -e INPUT_MARKDOWN_DIR -e INPUT_OUTPUT_DIR -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/doc-info/doc-info":"/github/workspace" mkrakowitzer/actions-makepdfs:latest
(node:1) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process! spawn /node_modules/puppeteer/.local-chromium/linux-782078/chrome-linux/chrome ENOENT


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:193:20)
    at ChildProcess.helper_js_1.helper.addEventListener (/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:185:85)
    at ChildProcess.emit (events.js:198:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

EDIT: I've now also tried some of the branches that are currently created through dependabot's open PR, but non work either.

**Comment by ghost** [comment]
Hello, I am also seeing the same issue

```
2020-12-17T11:26:17.2613951Z ##[group]Run mkrakowitzer/actions-makepdfs@v1.2
2020-12-17T11:26:17.2614492Z with:
2020-12-17T11:26:17.2614876Z   markdown_dir: pages
2020-12-17T11:26:17.2615262Z   output_dir: pdf
2020-12-17T11:26:17.2615653Z ##[endgroup]
2020-12-17T11:26:17.2654111Z ##[command]/usr/bin/docker run --name mkrakowitzeractionsmakepdfslatest_eabb30 --label 179394 --workdir /github/workspace --rm -e INPUT_MARKDOWN_DIR -e INPUT_OUTPUT_DIR -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/demo-gitpages/demo-gitpages":"/github/workspace" mkrakowitzer/actions-makepdfs:latest
2020-12-17T11:26:26.2144863Z (node:1) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process! spawn /node_modules/puppeteer/.local-chromium/linux-782078/chrome-linux/chrome ENOENT
2020-12-17T11:26:26.2146099Z 
2020-12-17T11:26:26.2146333Z 
2020-12-17T11:26:26.2147169Z TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
2020-12-17T11:26:26.2147899Z 
2020-12-17T11:26:26.2148577Z     at onClose (/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:193:20)
2020-12-17T11:26:26.2150136Z     at ChildProcess.helper_js_1.helper.addEventListener (/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:185:85)
2020-12-17T11:26:26.2151349Z     at ChildProcess.emit (events.js:198:13)
2020-12-17T11:26:26.2152236Z     at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
2020-12-17T11:26:26.2153112Z     at onErrorNT (internal/child_process.js:415:16)
2020-12-17T11:26:26.2153875Z     at process._tickCallback (internal/process/next_tick.js:63:19)
2020-12-17T11:26:26.2158797Z (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
2020-12-17T11:26:26.2161331Z (node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by geoffrey-vl** [comment]
I was able to solve the issue by fixing the version of puppeteer to 5.2.1 (which works with chromium 782078).
For users to use this, the latest docker image must be build and deployed.

Anyone interested can use my fork for now: 
```
- name: Create PDF
        # You may pin to the exact commit or the version.
        # uses: mkrakowitzer/actions-makepdfs@master
        uses: geoffrey-vl/actions-makepdfs@e14cca39763dc833d20fd40b2a1941196cb27716 
        with:
          # Location of markdown files in github repository (default is doc)
          markdown_dir: ...
          # Location to output PDF files to (default is tmp)
          output_dir: ...
```
